name: SaaSGuard

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scan:
    name: Run SaaSGuard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install || true
      - run: npx semgrep install || true
      - run: npx osv-scanner --version || echo "osv-scanner will run in script"
      - run: node scripts/main.js
      - uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: output/